apiVersion: v1
kind: PersistentVolume
metadata:
 name: nfs-pv
 namespace: test
 labels:
  type: nfs
spec:
 volumeMode: Filesystem
 capacity:
  storage: 3Gi
 accessModes:
  - ReadWriteMany
 nfs:
  server: 172.16.10.184
  path: /home/db_nfs/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: nfs-pvc
 namespace: test
spec:
 accessModes:
  - ReadWriteMany
 volumeMode: Filesystem
 resources:
  requests:
   storage: 3Gi
 storageClassName: ""
 selector:
  matchExpressions:
   - key: type
     operator: In
     values:
      - nfs
